### ISSUE TITLE
Long loading time

### ISSUE THREAD

**Issue by XxFluffyAsherxX** [leaningtech/browsercraft#3]
?

**Comment by bates64** [comment]
If it's not loading after a couple minutes, your network or machine is either slow or something has gone wrong.

You can watch the network requests proceed in the inspector:
<img width="557" alt="image" src="https://github.com/leaningtech/browsercraft/assets/9429556/0402a978-e9df-458a-8225-ddd0177459a9">

**Comment by XxFluffyAsherxX** [comment]
I cant access inspector, how can I help it load faster?

**Comment by bates64** [comment]
Which browser/OS are you using?

**Comment by bates64** [comment]
Please upgrade to Chrome 125. It's unlikely that this is a crash, though.
Which laptop/processor? It's possible that your machine's CPU is too slow to handle it

**Comment by XxFluffyAsherxX** [comment]
its a Lenovo Chromebook.

**Comment by bates64** [comment]
It's likely that your device isn't powerful enough to run Browsercraft, sorry.
